DevCycleHQ/java-server-sdk

src/main/java/com/devcycle/sdk/server/local/DVCClient.java
- this will be the default behaviour going forward
=> add local DVCClient class to be used for local bucketing

README.md, build.gradle, example/build.gradle, src/main/java/com/devcycle/sdk/server/common/model/PlatformData.java, src/main/java/com/devcycle/sdk/server/common/model/User.java, src/test/java/com/devcycle/sdk/server/cloud/DVCCloudClientTest.java, src/test/java/com/devcycle/sdk/server/local/LocalBucketingTest.java
- add hostname to `toString()` method in PlatformData
- populate the default platform data fields in User model with defaults from PlatformData
- bump to version 1.1.1
- remove retrieving sdk version from `build.gradle` as it is not compatible with our tests
- update README with cloud/local examples
- cleanup
=> DVC-4534 add hostname for platform data

README.md, build.gradle, example-cloud/build.gradle, src/main/java/com/devcycle/sdk/server/common/model/PlatformData.java, src/test/java/com/devcycle/sdk/server/cloud/DVCCloudClientTest.java
=> chore(release): 1.1.2

example-local/src/main/java/com/devcycle/example/java/sdk/app/controller/HelloWorld.java, src/main/java/com/devcycle/sdk/server/local/managers/EnvironmentConfigManager.java, src/main/java/com/devcycle/sdk/server/local/model/DVCLocalOptions.java
- rename to capitalize S in `Ms`
- keep older name but mark as deprecated
=> rename to configPollingIntervalMS and deprecate configPollingIntervalMs

README.md, build.gradle, src/main/java/com/devcycle/sdk/server/common/model/PlatformData.java, src/test/java/com/devcycle/sdk/server/cloud/DVCCloudClientTest.java
- bump WASM to version 1.2.28
- bump Java Server SDK version to 1.1.3
=> Release 1.1.3

src/main/java/com/devcycle/sdk/server/cloud/api/DVCCloudApiClient.java, src/main/java/com/devcycle/sdk/server/local/api/DVCLocalApiClient.java, src/main/java/com/devcycle/sdk/server/local/api/DVCLocalEventsApiClient.java
- adds URL override support for Cloud API Client, Local API Client and Local Events Client
=> [fix] add url override support

src/main/java/com/devcycle/sdk/server/cloud/api/DVCCloudClient.java, src/main/java/com/devcycle/sdk/server/local/api/DVCLocalClient.java
- add Event validation for `track` method
- remove return type for Cloud Client `track`
=> Track method fixes

README.md, build.gradle, src/main/java/com/devcycle/sdk/server/common/model/PlatformData.java, src/test/java/com/devcycle/sdk/server/cloud/DVCCloudClientTest.java
=> [release] 1.3.0

example-cloud/src/main/java/com/devcycle/example/java/sdk/app/controller/HelloWorld.java, example-cloud/src/main/resources/application.properties, example-cloud/src/main/resources/templates/fragments/flagDataDetails.html, example-cloud/src/main/resources/templates/home.html, example-local/src/main/java/com/devcycle/example/java/sdk/app/controller/HelloWorld.java, example-local/src/main/resources/application.properties, example-local/src/main/resources/templates/fragments/flagData.html, example-local/src/main/resources/templates/fragments/flagDataDetails.html, example-local/src/main/resources/templates/home.html, src/main/java/com/devcycle/sdk/server/cloud/api/DVCCloudClient.java, src/main/java/com/devcycle/sdk/server/local/api/DVCLocalClient.java, src/test/java/com/devcycle/sdk/server/cloud/DVCCloudClientTest.java, src/test/java/com/devcycle/sdk/server/local/DVCLocalClientTest.java
- Adding new default method to both the cloud and local clients to return the variable value (or default) without needing to interact with the Variable object.
Also touched up the the example apps
- the cloud example was broken and wasn't compiling
- Separate buttons for retrieving variable value and the Variable object
- Displaying the variable key on the UI
=> DVC-7288 Add Variable Value method

build.gradle
forgot to update the gradle.build to have the new 1.4.0 version #
=> update version to match release

benchmark/README.md, benchmark/pom.xml, benchmark/src/main/java/com/devcycle/MockServer.java, benchmark/src/main/java/com/devcycle/SDKBenchmark.java, benchmark/src/main/java/com/devcycle/VariableTest.java, benchmark/src/main/resources/fixture_large_config.json, src/main/java/com/devcycle/sdk/server/local/utils/ProtobufUtils.java
- Added a JMH benchmark sub-project for generating variable evaluation benchmarks
- Created a simple cmd line app to do sdk profiling
=> DVC-6640 sdk benchmark tool

src/main/java/com/devcycle/sdk/server/local/api/DVCLocalClient.java, src/test/java/com/devcycle/sdk/server/local/DVCLocalClientTest.java
the isInitialized boolean didn't mean anything so I reworked the local client to base "initialized" on whether or not it has a config properly loaded into the EnvironmentConfigManager
=> Changed concept of client init

src/main/java/com/devcycle/sdk/server/local/model/Project.java
this config property no longer exists so we can remove support
=> Remove SDKTypeVisibility property from config

README.md, benchmark/pom.xml, build.gradle, example-cloud/build.gradle, example-local/build.gradle, src/main/java/com/devcycle/sdk/server/common/model/PlatformData.java, src/test/java/com/devcycle/sdk/server/cloud/DVCCloudClientTest.java
Releasing new minor version with the custom logger support
=> bumping version numbers

README.md, benchmark/pom.xml, build.gradle, example-cloud/build.gradle, example-local/build.gradle, src/main/java/com/devcycle/sdk/server/common/model/PlatformData.java, src/test/java/com/devcycle/sdk/server/cloud/DVCCloudClientTest.java
=> Release 1.6.2

README.md
- improved doc intro
- added linux/aarch64 to requirements
- fixed usage links
=> chore: documentation fixes

build.gradle
- revert from 2.1.1 to 2.1.0 so the release action works
=> fix: attempt release that got stuck in the middle

.github/workflows/release.yml, .github/workflows/test-examples.yml, .github/workflows/unit-test.yml
- update release action to use v2.3.0
- update gradle action to use v3
- update setup-java to use v4
=> chore: Fix release action

build.gradle
bump protobuf and openfeature versions
=> chore: bump protobuf and openfeature

.github/workflows/checks.yml, .github/workflows/test-examples.yml, .github/workflows/unit-test.yml
=> chore: pin actions to git sha
