build.gradle
src/main/java/com/devcycle/sdk/server/api/DVCClient.java
src/main/java/com/devcycle/sdk/server/model/Feature.java
src/main/java/com/devcycle/sdk/server/model/User.java
src/main/java/com/devcycle/sdk/server/model/Variable.java
src/test/java/com/devcycle/sdk/server/api/DVCClientTest.java

- allows for easy identification of which variation of a given feature is being served to the user
- add `@JsonIgnoreProperties(ignoreUnknown = true)` to Feature, User and Variable models
- version bump to 1.0.5

add variationName and variationKey to Feature model

---

example/src/main/java/com/devcycle/example/java/sdk/app/controller/HelloWorld.java
src/main/java/com/devcycle/sdk/server/local/api/DVCLocalApiClient.java
src/main/java/com/devcycle/sdk/server/local/api/DVCLocalClient.java
src/main/java/com/devcycle/sdk/server/local/managers/EventQueueManager.java
src/main/java/com/devcycle/sdk/server/local/model/BucketedUserConfig.java
src/test/java/com/devcycle/sdk/server/local/DVCLocalClientTest.java

- instead of throwing Exceptions in `DVCLocalClient`, now logs errors
- cleanup example app for local user

DVC-4466 Add Error Handling to Java Local Bucketing SDK

---

src/main/java/com/devcycle/sdk/server/common/model/ErrorResponse.java
src/main/java/com/devcycle/sdk/server/common/model/Feature.java
src/main/java/com/devcycle/sdk/server/common/model/ProjectConfig.java
src/main/java/com/devcycle/sdk/server/common/model/User.java
src/main/java/com/devcycle/sdk/server/common/model/Variable.java
src/main/java/com/devcycle/sdk/server/local/model/Project.java

- allow for JSON parsing of a Project Config with unknown root level properties
- add support for local bucketing to generate proper payloads to handle `project.settings.optIn.poweredByAlignment` attribute

fix to ignore new properties added at the root level of a project config

---

README.md
build.gradle
src/main/java/com/devcycle/sdk/server/common/model/PlatformData.java
src/test/java/com/devcycle/sdk/server/cloud/DVCCloudClientTest.java

- Update WASM to `1.3.3`
- Renamed all instances of `envKey` / `env_key` /  `environmentKey` / etc, to `sdkKey` to be consistent with all DevCycle SDKs. #47

Release 1.2.0

---

src/main/java/com/devcycle/sdk/server/common/model/DVCResponse.java

- test harness was failing in `getResponse` on the `EventQueueManager` because the test harness tests weren't passing in a body
- pass in a body, and ignore unknown properties

DVC-6296 ignore unknown properties dvc response

---

src/main/java/com/devcycle/sdk/server/cloud/api/DVCCloudClient.java
src/main/java/com/devcycle/sdk/server/local/api/DVCLocalClient.java

- the `event == null` check wasn't properly protecting against invalid event types

properly check event type and throw exception for invalid events

---

build.gradle
pom.xml
src/main/java/com/devcycle/sdk/server/local/bucketing/LocalBucketing.java

- update local bucketing to use address pinning
- update to wasmtime `0.14` and jackson `2.14.2`

[fix] DVC-6373: use address pinning in Local Bucketing

---

src/main/java/com/devcycle/sdk/server/local/api/DVCLocalClient.java
src/main/java/com/devcycle/sdk/server/local/bucketing/LocalBucketing.java
src/test/java/com/devcycle/sdk/server/helpers/LocalConfigServer.java
src/test/java/com/devcycle/sdk/server/helpers/TestDataFixtures.java
src/test/java/com/devcycle/sdk/server/local/DVCLocalClientTest.java
src/test/resources/fixture_large_config.json
src/test/resources/fixture_small_config.json
src/test/resources/fixture_small_config_special_characters.json

- switched the SDK from getting all variables to using new variableForUser function in the WASM
- update logic to match what is done in Go/.Net/Ruby
- updated to latest WASM file
- Added data fixture files to load via class path instead of hardcoded variable
- Added large fixture file used for testing other SDKs like Go and DotNet
- Changed the unit tests to use an actual config web server to properly test initialization and variable evaluation

DVC-6643 - Update variable() to use new WASM variableForUser function

---

src/main/java/com/devcycle/sdk/server/local/bucketing/LocalBucketing.java

Adding synchronized keywords to all public methods touching the WASM

Thread safety around LocalBucketing

---

src/main/java/com/devcycle/sdk/server/local/api/DVCLocalClient.java

Checks that the java runtime is x86 and 64-bit and logs an error if it isn't

Verify the java runtime when local bucketing client initializes

---

src/main/java/com/devcycle/sdk/server/local/utils/ProtobufUtils.java
src/test/java/com/devcycle/sdk/server/helpers/TestDataFixtures.java
src/test/java/com/devcycle/sdk/server/local/DVCLocalClientTest.java
src/test/resources/fixture_small_config_custom_data_bucketing.json

There was a bug in the creation of the protobuf user object where the privateCustomData map would overwrite the customData map property. This causes bucketing depending on customData properties to fail.
Also added some unit tests around the setting and evaluation of custom data for bucketing.

Fixed bug with customData not set properly in Protobuf message

---

src/main/java/com/devcycle/sdk/server/local/bucketing/LocalBucketing.java
src/test/java/com/devcycle/sdk/server/local/DVCLocalClientTest.java

fixed the generateBucketedConfigForUser to use the UTF8 version of the WASM function to match the rest of the UTF8 support in LocalBucketing.java

DVC-7512 - fix UTF8 issues with generateBucketConfigForUser

---

src/main/java/com/devcycle/sdk/server/cloud/api/DVCCloudClient.java
src/main/java/com/devcycle/sdk/server/common/exception/DVCException.java
src/main/java/com/devcycle/sdk/server/common/model/HttpResponseCode.java
src/main/java/com/devcycle/sdk/server/common/model/User.java
src/main/java/com/devcycle/sdk/server/local/api/DVCLocalClient.java
src/main/java/com/devcycle/sdk/server/local/managers/EnvironmentConfigManager.java
src/main/java/com/devcycle/sdk/server/local/managers/EventQueueManager.java

multiple changes to the SDK so it behaves in a way to support the test harness
- added retries to cloud SDK and local bucketing config loading
- Fixed exception handling/reporting
- Fixed issues with SDK key validation
- resolved data type mismatches
- refactored some copy/paste code
This SDK still needs an overhaul on how it does logging but that is tracked in another ticket.

DVC-7132 fix java test harness

---

README.md
src/main/java/com/devcycle/sdk/server/cloud/api/DVCCloudClient.java
src/main/java/com/devcycle/sdk/server/cloud/model/DVCCloudOptions.java
src/main/java/com/devcycle/sdk/server/common/logging/DVCLogger.java
src/main/java/com/devcycle/sdk/server/common/logging/IDVCLogger.java
src/main/java/com/devcycle/sdk/server/common/logging/SimpleDVCLogger.java
src/main/java/com/devcycle/sdk/server/common/model/PlatformData.java
src/main/java/com/devcycle/sdk/server/local/api/DVCLocalClient.java
src/main/java/com/devcycle/sdk/server/local/bucketing/LocalBucketing.java
src/main/java/com/devcycle/sdk/server/local/managers/EnvironmentConfigManager.java
src/main/java/com/devcycle/sdk/server/local/managers/EventQueueManager.java
src/main/java/com/devcycle/sdk/server/local/model/DVCLocalOptions.java
src/test/java/com/devcycle/sdk/server/local/DVCLocalClientTest.java

Introduced a custom logging system that still defaults to **stdout**, but is easy for any dev to override and customize. 
Given that there a half dozen "standard" packages for logging in Java with mixed interoperability, I didn't want to create a dependency for one of them in the SDK. Instead I added a simple interface that users can implement in order to redirect the SDKs log output to their own internal logging system such as Java Logging, log4j2, SLF4J, etc
This mimics a similar system we provide in the Go SDK

Add customizable logging system

---

README.md
benchmark/pom.xml
build.gradle
example-cloud/build.gradle
example-local/build.gradle
src/main/java/com/devcycle/sdk/server/common/model/PlatformData.java
src/test/java/com/devcycle/sdk/server/cloud/DVCCloudClientTest.java

- updated wasmtime to 0.15.0 in order to reduce `glibc` requirement to 2.30 and make local bucketing more compatible
- bumped sdk version to 1.6.1

Update wasmtime dependency

---

README.md
src/main/java/com/devcycle/sdk/server/local/model/DVCLocalOptions.java
src/test/java/com/devcycle/sdk/server/local/DVCLocalClientTest.java

Ticket: https://taplytics.atlassian.net/browse/DVC-7985
Setting up custom logging on a DVCLocalClient when events are enabled will cause the client to generate a JSON serialization exception during client creation.  
Added `@JsonIgnore` annotation to the property so it doesn't get included in options serialization during creation of the event queue.
Introduced a custom logger to the DVCLocalClient to ensure it works properly

[fix] Setting custom logger on DVCLocalClient causes exception

---

src/main/java/com/devcycle/sdk/server/cloud/api/DVCCloudApiClient.java
src/main/java/com/devcycle/sdk/server/cloud/model/DVCCloudOptions.java
src/main/java/com/devcycle/sdk/server/common/api/APIUtils.java
src/main/java/com/devcycle/sdk/server/common/api/IRestOptions.java
src/main/java/com/devcycle/sdk/server/common/interceptor/CustomHeaderInterceptor.java
src/main/java/com/devcycle/sdk/server/local/api/DVCLocalApiClient.java
src/main/java/com/devcycle/sdk/server/local/api/DVCLocalEventsApiClient.java
src/main/java/com/devcycle/sdk/server/local/model/DVCLocalOptions.java
src/test/java/com/devcycle/sdk/server/local/DVCLocalClientTest.java
src/test/java/com/devcycle/sdk/server/utils/ByteConversionUtilsTest.java

Added interface that can be implemented to inject custom headers and SSL configuration into API calls for the local and cloud client. 
Developers can implement the IRestOptions interface and supply it with the options object for either the cloud or local bucketing client. When supplied, this object will be used to setup the OKHttpClient used internally to add custom headers and cert information.
Code paths are fully optional so this new feature will be safe to merge without negatively impacting existing SDK users.

DVC-8003 custom header and ssl support

---

benchmark/pom.xml
src/main/java/com/devcycle/sdk/server/common/interceptor/AuthorizationHeaderInterceptor.java

RBC noticed that if they use the new IRestOptions interface to inject headers and then add their own Authorization header with an APIGEE token, the SDK will still add our own Authorization header with SDK key for Event API requests.  
Including two headers with the same name goes against RFC 7230/7235 and will be rejected by some servers.  
They need to set their own Authorization header and then have the DevCycle key provided in a different, known header which they can rewrite at the proxy level. To mitigate this the code detects the scenario and rename `Authorization` to `DevCycle-Authorization`, with the assumption the developer will use some kind of rewrite rule in their proxy before making the call to the DevCycle Events API

[fix] Prevent multiple authorization headers in Events API requests

---

.github/workflows/release.yml

- updated the script to use the new github action
- using new pre-release step
- Adding logging when release is complete

fix: revised github automated release

---

README.md
build.gradle
src/main/java/com/devcycle/sdk/server/local/api/DVCLocalClient.java
src/main/java/com/devcycle/sdk/server/local/managers/EnvironmentConfigManager.java
src/main/java/com/devcycle/sdk/server/local/managers/EventQueueManager.java

This updates wasmtime-java to v0.17.0 and updates the log level for an error log that was too low to see if the INFO level was filtered out.
I also updated a few other logs that seemed to be at the wrong level - I'm open to changing them back though.

chore: Update wasmtime-java and tweak logs (DVC 8452)

---

build.gradle

Doing this so that the release action will create a commit that actually has changes made when updating from 2.1.0 to 2.1.1

fix: the build that was broken by the automated release commit

---

src/main/java/com/devcycle/sdk/server/local/managers/EnvironmentConfigManager.java
src/main/java/com/devcycle/sdk/server/local/model/DevCycleLocalOptions.java

Depricate `enableBetaRealtimeUpdates` and add new `disableRealtimeUpdates` option. SSE connections are now enabled by default and will fall back to polling against the config CDN.

feat: set SSE connections as the default

---

.github/workflows/release.yml

fix: release workflow, combined into closeAndReleaseSonatypeStagingRepository

---

.github/workflows/unit-test.yml

Potential fix for [https://github.com/DevCycleHQ/java-server-sdk/security/code-scanning/5](https://github.com/DevCycleHQ/java-server-sdk/security/code-scanning/5)
To fix the issue, we will add a `permissions` block at the root of the workflow file. Since the workflow only performs read operations (e.g., checking out the code and running tests), we will set `contents: read` as the minimal required permission. This ensures the workflow has the least privileges necessary to function correctly.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

chore: Potential fix for code scanning alert no. 5: Workflow does not contain permissions

---

src/main/java/com/devcycle/sdk/server/cloud/api/DevCycleCloudClient.java
src/main/java/com/devcycle/sdk/server/common/exception/AfterHookError.java
src/main/java/com/devcycle/sdk/server/common/exception/BeforeHookError.java
src/main/java/com/devcycle/sdk/server/common/model/EvalHook.java
src/main/java/com/devcycle/sdk/server/common/model/EvalHooksRunner.java
src/main/java/com/devcycle/sdk/server/common/model/HookContext.java
src/main/java/com/devcycle/sdk/server/local/api/DevCycleLocalClient.java
src/test/java/com/devcycle/sdk/server/cloud/DevCycleCloudClientTest.java
src/test/java/com/devcycle/sdk/server/cloud/EvalHooksRunnerTest.java
src/test/java/com/devcycle/sdk/server/local/DevCycleLocalClientTest.java

- added eval hooks to Cloud + Local Java SDK

feat: added evaluation hooks

---

src/examples/java/com/devcycle/examples/LocalExample.java
src/main/java/com/devcycle/sdk/server/cloud/api/DevCycleCloudApiClient.java
src/main/java/com/devcycle/sdk/server/cloud/api/DevCycleCloudClient.java
src/main/java/com/devcycle/sdk/server/common/api/ObjectMapperUtils.java
src/main/java/com/devcycle/sdk/server/common/model/HookContext.java
src/main/java/com/devcycle/sdk/server/common/model/ProjectConfig.java
src/main/java/com/devcycle/sdk/server/local/api/DevCycleLocalApiClient.java
src/main/java/com/devcycle/sdk/server/local/api/DevCycleLocalClient.java
src/main/java/com/devcycle/sdk/server/local/api/DevCycleLocalEventsApiClient.java
src/main/java/com/devcycle/sdk/server/local/managers/EnvironmentConfigManager.java
src/main/java/com/devcycle/sdk/server/local/model/ConfigMetadata.java
src/main/java/com/devcycle/sdk/server/local/model/EnvironmentMetadata.java
src/main/java/com/devcycle/sdk/server/local/model/ProjectMetadata.java
src/test/java/com/devcycle/sdk/server/cloud/DevCycleCloudClientTest.java
src/test/java/com/devcycle/sdk/server/cloud/EvalHooksRunnerTest.java
src/test/java/com/devcycle/sdk/server/helpers/LocalConfigServer.java
src/test/java/com/devcycle/sdk/server/local/DevCycleLocalClientTest.java

- add config metadata for project and environment information to be added to the evaluation context
- move the current config etag and last updated inside the config metadata fields 
- add accessor to the local client for getting metadata
- use Objectmapper utils to keep json serialization and unknown property configuration to be centralized. When trying to serialize the project, I was getting issues for unknown properties under `project.settings` for `obfuscation` field and was requiring me to add the unknown fields property to project settings and project so instead centralized the serialization 
- tested using the local example

feat: add config metadata

---

src/main/java/com/devcycle/sdk/server/cloud/api/DevCycleCloudClient.java
src/main/java/com/devcycle/sdk/server/common/model/EvalHook.java
src/main/java/com/devcycle/sdk/server/common/model/EvalHooksRunner.java
src/main/java/com/devcycle/sdk/server/common/model/PlatformData.java
src/main/java/com/devcycle/sdk/server/local/api/DevCycleLocalClient.java
src/main/java/com/devcycle/sdk/server/local/model/VariableMetadata.java
src/test/java/com/devcycle/sdk/server/cloud/DevCycleCloudClientTest.java
src/test/java/com/devcycle/sdk/server/cloud/EvalHooksRunnerTest.java
src/test/java/com/devcycle/sdk/server/local/DevCycleLocalClientTest.java

- chore: add Builder.Default to address build warning
- fix: update local bucketing hooks to work with `SDKVariable_PB` and add cloud hooks that work with `Variable<T>`

fix: update hooks to include feature
